apiVersion: v1
baseDomain: okd.virtualbox
metadata:
  name: okd-virtualbox
networking:
  machineCIDR: 192.168.5.0/24
  networkType: OVNKubernetes
compute:
  - name: worker
    replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.5.101
    ingressVIP: 192.168.5.102
    provisioningBridge: provisioning
    provisioningNetworkCIDR: 172.22.0.0/24
    provisioningNetworkInterface: eth2
    hosts:
      - name: master-1
        role: master
        bmc:
          address: ipmi://127.0.1.1
          username: admin
          password: admin
        bootMACAddress: 08:00:27:fe:ee:6a
        bootMode: legacy
      - name: master-2
        role: master
        bmc:
          address: ipmi://127.0.1.2
          username: admin
          password: admin
        bootMACAddress: 08:00:27:8e:e3:1b
        bootMode: legacy
      - name: master-3
        role: master
        bmc:
          address: ipmi://127.0.1.3
          username: admin
          password: admin
        bootMACAddress: 08:00:27:58:db:48
        bootMode: legacy
      - name: worker-1
        role: worker
        bmc:
          address: ipmi://127.0.1.4
          username: admin
          password: admin
        bootMACAddress: 08:00:27:b3:a5:85
        bootMode: legacy
      - name: worker-2
        role: worker
        bmc:
          address: ipmi://127.0.1.5
          username: admin
          password: admin
        bootMACAddress: 08:00:27:70:90:71
        bootMode: legacy
pullSecret: '<pull_secret>'
sshKey: '<ssh_pub_key>'
